language: cpp
compiler: clang++

before_install:
  - sudo apt-get install libgmsh-dev
  - sudo apt-get install libeigen3-dev
  - dpkg -L libgmsh-dev
  - dpkg -L libeigen3-dev
install: skip

script:
  - make -C Assignments/A1
  - ./Assignments/A1/A1.out
