language: cpp
compiler: clang++
os: osx

before_install:
  - brew update
  - brew install gmsh
  - brew install eigen
  - brew install dpkg
  - brew upgrade boost
  - ls /usr/include
  - ls /usr/lib
  - ls /usr/local/include
  - ls /usr/local/lib
  - gmsh -version

install: skip

script:
  - cd Assignments/A1
  - make
  - gmsh -2 -clscale 1.0 -o TestMesh.msh TestMesh.geo
  - ./A1.out "./TestMesh.msh" "AntennatPositions.txt" "4e9"
  - gmsh -2 -clscale 0.3 -o TestMesh.msh TestMesh.geo
  - ./A1.out "./TestMesh.msh" "AntennatPositions.txt" "4e9"
  - gmsh -2 -clscale 0.1 -o TestMesh.msh TestMesh.geo
  - ./A1.out "./TestMesh.msh" "AntennatPositions.txt" "4e9"
