language: cpp
compiler: clang++
os: osx

before_install:
  - brew update
  - brew install gmsh
  - brew install eigen
  - brew install dpkg
  - brew upgrade boost
  - ls /usr/include
  - ls /usr/lib
  - ls /usr/local/include
  - ls /usr/local/lib
  - gmsh -version

install: skip

script:
  - cd Assignments/A1
  - make
  - ./A1.out "./TestMesh.msh"
