language: cpp
compiler: clang++
os: osx

before_install:
  - brew update
  - brew install gmsh
  - brew install eigen
  - brew install dpkg
  - brew install boost
  - ls /usr/include
  - ls /usr/lib
  - ls /usr/local/include
  - ls /usr/local/lib
  - gmsh -version

install: skip

script:
  - make -C Assignments/A1
  - ./Assignments/A1/A1.out "./Assignments/A1/TestMesh.msh"
