language: cpp
compiler: clang++
os: osx

before_install:
  - brew update
  - brew install gmsh
  - brew install eigen
  - brew upgrade boost

install: skip

script:
  - cd Assignments/A1
  - make
  - gmsh -2 -clscale 1.0 -o Ring.msh Ring.geo
  - ./A1.out "Ring.msh" "Tag2EpsRel.txt" "Antennas.txt" 1e9 "ProbePositions.txt"
  - gmsh -2 -clscale 0.5 -o Ring.msh Ring.geo
  - ./A1.out "Ring.msh" "Tag2EpsRel.txt" "Antennas.txt" 1e9 "ProbePositions.txt"
  - gmsh -2 -clscale 0.2 -o Ring.msh Ring.geo
  - ./A1.out "Ring.msh" "Tag2EpsRel.txt" "Antennas.txt" 1e9 "ProbePositions.txt"
