language: cpp
compiler: clang++
os: osx

before_install:
  - HOMEBREW_NO_AUTO_UPDATE=1 brew install gmsh
  - HOMEBREW_NO_AUTO_UPDATE=1 brew install eigen
  - gmsh -version

install: skip

script:
  - make -C Assignments/A1
  - ./Assignments/A1/A1.out
