language: cpp
compiler: clang++
os: osx

before_install:
  - brew install gmsh
  - brew install eigen
  - brew upgrade boost
  - brew upgrade gmsh
  - brew upgrade eigen
  - brew upgrade boost

install: skip

script:
  - cd Assignments/A1
  - make
  - gmsh -2 -clscale 1.0 -o Ring.msh Ring.geo
  - ./A1.out "Ring.msh" "Tag2EpsRel.txt" "Antennas.txt" 3e9
  - gmsh -2 -clscale 0.3 -o Ring.msh Ring.geo
  - ./A1.out "Ring.msh" "Tag2EpsRel.txt" "Antennas.txt" 3e9
  - gmsh -2 -clscale 0.1 -o Ring.msh Ring.geo
  - ./A1.out "Ring.msh" "Tag2EpsRel.txt" "Antennas.txt" 3e9
