language: cpp
compiler: clang++
os: osx

before_install:
  - export HOMEBREW_NO_AUTO_UPDATE = 1
  - brew install gmsh
  - brew install eigen
  - dpkg -L gmsh
  - gmsh -version
  - dpkg -L eigen

install: skip

script:
  - make -C Assignments/A1
  - ./Assignments/A1/A1.out
